name: ${project.name}
main: com.poixson.backrooms.BackroomsPlugin
version: '${project.version}'
api-version: '${bukkit-short-version}'
load: STARTUP
dependencies:
    server:
        VitalCore:
            load: BEFORE
            required: true
        Multiverse-Core:
            load: BEFORE
            required: true
        MoreFoods:
            load: BEFORE
            required: false
        dynmap:
            load: BEFORE
            required: false
        Vault:
            load: BEFORE
            required: false
authors: lorenzop
website: ${project.url}
description: ${project.description}
permissions:
    backrooms.*:
        default: op
        description: Gives access to all backrooms commands.
        children:
            backrooms.reconvergence:       true
            backrooms.noclip.front:        true
            backrooms.noclip.back:         true
            backrooms.cmd.noclip.front:    true
            backrooms.cmd.noclip.back:     true
            backrooms.cmd.noclip.others:   true
            backrooms.cmd.noclip.specific: true
            backrooms.level_111.button:    true
    backrooms.reconvergence:
        default: op
        description: Allow access to the /reconvergence command
    backrooms.noclip.front:
        default: true
        description: Allow players to no-clip by suffocation in the frontrooms.
    backrooms.noclip.back:
        default: true
        description: Allow players to no-clip by suffocation in the backrooms.
    backrooms.cmd.noclip.front:
        default: op
        description: Allow players to no-clip from the frontrooms to the backrooms using the /noclip command.
    backrooms.cmd.noclip.back:
        default: op
        description: Allow players to no-clip inside the backrooms using the /noclip command.
    backrooms.cmd.noclip.others:
        default: op
        description: No-Clip other players into the backrooms with the /noclip command.
    backrooms.cmd.noclip.specific:
        default: op
        description: No-Clip to a specific backrooms level with the /noclip command.
    backrooms.level_111.button:
        default: true
        description: Allow players to teleport into level 111 run for your life.
